name: pluto_grid_export
description: CSV export for PlutoGrid.
version: 0.0.1-pre
homepage: https://bosskmk.github.io
repository: https://github.com/bosskmk/pluto_grid/packages/pluto_grid_export

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pluto_grid: ^3.0.0-0.pre
  csv: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0
  build_runner: ^2.1.10
  flutter_lints: ^2.0.1
