name: pluto_grid
description: PlutoGrid is datagrid for flutter. It is developed with Windows, Web first. There are plans to support Android and iOS as well.
version: 0.1.1
homepage: https://bosskmk.github.io
repository: https://github.com/bosskmk/pluto_grid

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1
  rxdart: ^0.24.1
  linked_scroll_controller: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
