name: Publish

on:
  push:
    branches:
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Without this, there are no files in the directory.
    - uses: actions/checkout@v2

    # getting for branch name
    - uses: nelonoel/branch-name@v1.0.1

    # using flutter
    - uses: subosito/flutter-action@v1
    - run: flutter channel dev
    - run: flutter upgrade
    - run: dart --version
    - run: flutter --version
    - run: flutter pub get
    - run: flutter test

    # delete unnecessary directories
    - run: |
        rm -rf ./test
        rm -rf ./tool

    # formatting
    - run: dartfmt -w .

    # publish to pub.dev
    - name: publish
      uses: sakebook/actions-flutter-pub-publisher@v1.3.1
      with:
        credential: ${{ secrets.PUB_CREDENTIAL_JSON }}
        flutter_package: true
        skip_test: true
        dry_run: false

    # tagging version
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "${{ env.BRANCH_NAME }}"
        git tag "${{ env.BRANCH_NAME }}"
        git push origin "${{ env.BRANCH_NAME }}"
